"""remove ask reference and comparison context

Revision ID: 0b42511d6bb2
Revises: 0c0ef975243b
Create Date: 2026-05-11 16:29:07.419051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b42511d6bb2'
down_revision = '0c0ef975243b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ask_messages', schema=None) as batch_op:
        batch_op.drop_column('reference_context')
        batch_op.drop_column('comparison_context')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ask_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comparison_context', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reference_context', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
