"""create ask messages table

Revision ID: 0c0ef975243b
Revises: d70637232e21
Create Date: 2026-05-11 16:09:41.800099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0ef975243b'
down_revision = 'd70637232e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ask_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('user_context', sa.Text(), nullable=True),
    sa.Column('reference_context', sa.Text(), nullable=True),
    sa.Column('comparison_context', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ask_messages')
    # ### end Alembic commands ###
