"""create reference documents table

Revision ID: f97af9163d39
Revises: 
Create Date: 2026-05-06 16:12:08.313705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97af9163d39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('exam_name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=30), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference_documents')
    # ### end Alembic commands ###
